# Generated by Django 4.1.7 on 2023-02-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('roll_no', models.CharField(max_length=3)),
                ('mobile_no', models.CharField(max_length=10)),
            ],
        ),
    ]
