# Generated by Django 3.2.12 on 2023-02-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0006_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='roll_no',
            new_name='password',
        ),
    ]
